name: ODGen
description: Run ODGen on your project

inputs:
  root:
    description: The root of the project to analyze.
    required: false
    default: .
  timeout:
    description: The maximum duration of the analysis in seconds.
    required: false
    default: 300 # seconds, 5 minutes
  vulnerability_type:
    description: The type(s) of vulnerability to scan for (comma- or newline-separated).
    required: true

runs:
  using: docker
  image: Dockerfile
  entrypoint: /app/run.sh
  args:
    - ${{inputs.root}}
    - ${{inputs.vulnerability_type}}
    - ${{inputs.timeout}}
