name: ODGen
description: Run ODGen on your project

inputs:
  root:
    description: The root of the project to analyze.
    required: false
    default: .
  timeout:
    description: The maximum duration of the analysis in seconds.
    required: false
    default: 900 # seconds, 15 minutes

runs:
  using: composite
  steps:
    - shell: bash
      run: echo '::warning::ericcornelissen/odgen-action/all has been deprecated in favor of using ericcornelissen/odgen-action with a list of vulnerability types'
    - uses: ericcornelissen/odgen-action@v1.1.1
      with:
        root: ${{inputs.root}}
        timeout: ${{inputs.timeout}}
        vulnerability_type: |
          os_command
          code_exec
          proto_pollution
          ipt
          xss
          path_traversal
