name: ODGen
description: Run ODGen on your project

inputs:
  root:
    description: The root of the project to analyze.
    required: false
    default: .
  timeout:
    description: The maximum duration of the analysis in seconds.
    required: false
    default: 900 # seconds, 15 minutes

runs:
  using: composite
  steps:
    ## Enable on next release
    # - name: Scan for Path Traversal vulnerabilities
    #   uses: ericcornelissen/odgen-action@14-script-to-run
    #   with:
    #     root: ${{inputs.root}}
    #     timeout: ${{steps.timeout.outputs.value}}
    #     vulnerability_type: |
    #       os_command
    #       code_exec
    #       proto_pollution
    #       ipt
    #       xss
    #       path_traversal
    - shell: bash
      run: echo '::warn::ericcornelissen/odgen-action/all has been deprecated in favor of ericcornelissen/odgen-action with a list of vulnerability types'
    - name: Compute individual timeout
      id: timeout
      shell: bash
      run: echo "value=$(($TOTAL/$JOBS))" >>"${GITHUB_OUTPUT}"
      env:
        JOBS: 6
        TOTAL: ${{inputs.timeout}}
    - name: Scan for Command Injection vulnerabilities
      uses: ericcornelissen/odgen-action@v1.0.4
      with:
        root: ${{inputs.root}}
        timeout: ${{steps.timeout.outputs.value}}
        vulnerability_type: os_command
    - name: Scan for Code Injection vulnerabilities
      uses: ericcornelissen/odgen-action@v1.0.4
      with:
        root: ${{inputs.root}}
        timeout: ${{steps.timeout.outputs.value}}
        vulnerability_type: code_exec
    - name: Scan for Prototype Pollution vulnerabilities
      uses: ericcornelissen/odgen-action@v1.0.4
      with:
        root: ${{inputs.root}}
        timeout: ${{steps.timeout.outputs.value}}
        vulnerability_type: proto_pollution
    - name: Scan for Internal Property Tampering vulnerabilities
      uses: ericcornelissen/odgen-action@v1.0.4
      with:
        root: ${{inputs.root}}
        timeout: ${{steps.timeout.outputs.value}}
        vulnerability_type: ipt
    - name: Scan for Cross-Site Scripting vulnerabilities
      uses: ericcornelissen/odgen-action@v1.0.4
      with:
        root: ${{inputs.root}}
        timeout: ${{steps.timeout.outputs.value}}
        vulnerability_type: xss
    - name: Scan for Path Traversal vulnerabilities
      uses: ericcornelissen/odgen-action@v1.0.4
      with:
        root: ${{inputs.root}}
        timeout: ${{steps.timeout.outputs.value}}
        vulnerability_type: path_traversal
