name: Test
on:
  pull_request: ~
  push:
    branches:
      - main

permissions: read-all

jobs:
  base-error:
    name: Base (error)
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - vulnerability_type: os_command
            root: ./ODGen/tests/packages/command_injection/multi_file
          - vulnerability_type: proto_pollution
            root: ./ODGen/tests/packages/prototype_pollution/confucious@0.0.12
          - vulnerability_type: os_command, proto_pollution
            root: ./ODGen/tests/packages/command_injection/multi_file
          - vulnerability_type: |
              proto_pollution
              os_command
            root: ./ODGen/tests/packages/command_injection/multi_file
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
          submodules: recursive
      - name: Run ODGen
        uses: ./
        id: odgen
        continue-on-error: true
        with:
          vulnerability_type: ${{matrix.vulnerability_type}}
          root: ${{matrix.root}}
      - name: Expect failure
        if: steps.odgen.outcome == 'success'
        run: exit 1
  base-pass:
    name: Base (pass)
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - vulnerability_type: proto_pollution
            root: ./ODGen/tests/packages/command_injection/multi_file
          - vulnerability_type: os_command
            root: ./ODGen/tests/packages/prototype_pollution/confucious@0.0.12
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
          submodules: recursive
      - name: Run ODGen
        uses: ./
        with:
          vulnerability_type: ${{matrix.vulnerability_type}}
          root: ${{matrix.root}}
  all-error:
    name: All (error)
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - root: ./ODGen/tests/packages/prototype_pollution/confucious@0.0.12
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
          submodules: recursive
      - name: Run ODGen
        uses: ./all/
        id: odgen
        continue-on-error: true
        with:
          root: ${{matrix.root}}
      - name: Expect failure
        if: steps.odgen.outcome == 'success'
        run: exit 1
  all-pass:
    name: All (pass)
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - root: ./patches
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
          submodules: recursive
      - name: Run ODGen
        uses: ./all/
        with:
          root: ${{matrix.root}}
