name: Test
on:
  pull_request: ~
  push:
    branches:
      - main

permissions: read-all

jobs:
  e2e:
    name: End-to-end
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          # expect: finds a vulnerability
          - vulnerability_type: os_command
            root: ./ODGen/tests/packages/command_injection/multi_file
          - vulnerability_type: proto_pollution
            root: ./ODGen/tests/packages/prototype_pollution/confucious@0.0.12

          # expect: finds no vulnerability
          - vulnerability_type: proto_pollution
            root: ./ODGen/tests/packages/command_injection/multi_file
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: recursive
      - name: Run ODGen
        uses: ./
        with:
          vulnerability_type: ${{matrix.vulnerability_type}}
          root: ${{matrix.root}}
  e2e-all:
    name: End-to-end (all)
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: recursive
      - name: Run ODGen
        uses: ./all/
        with:
          root: ./ODGen/tests/packages/command_injection/multi_file
